### ISSUE TITLE
Running coverage but coverage is empty

### ISSUE THREAD

**Issue by maxknee** [t2ym/web-component-tester-istanbul#5]
```{
  "suites": ["app/**/test", "app/js/**/test"],
  "testTimeout": 300000,
  "plugins": {
    "local": {
      "browsers": ["firefox"],
      "browserOptions": {
        "firefox": ["--headless"]
      }
    },
    "istanbul": {
      "dir": "./coverage",
      "reporters": ["json", "lcov", "cobertura"],
      "include": [
        "/app/elements/**/*.js",
        "/app/js/**/*.js"
      ]
    },
    "sauce": {
      "disabled": true
    }
  }
}
```
```├─┬ @t2ym/web-component-tester@6.0.2 (git+ssh://git@github.com/t2ym/web-component-tester.git#3da9cd7010e1cc6d89c4a5f4959b5af5ce6cbe0d)
│ ├── polyserve@0.19.1-istanbul.3  (git+https://github.com/t2ym/polyserve.git#767aa4d2909b5438ac31c1d215ea1ec9f9aacd3e)
─┬ wct-istanbul@0.12.4
│ └── polyserve@0.19.1-istanbul.3  (git://github.com/t2ym/polyserve.git#767aa4d2909b5438ac31c1d215ea1ec9f9aacd3e)
```

Is there anything extra I need to do?

**Comment by t2ym** [comment]
@maxknee You can check the internal behaviors with `--verbose` option to `wct`

## Configurations to check
- `plugins.istanbul.include` may need calibration to match with the target files
  - Loose matching rules like `"**/app/elements/**/*.js"` might be effective
- I have not checked `"json"` and `"cobertura"` reporters.  You can try the default `"text-summary", "lcov"`

## Expected `--verbose` log outputs (extracted)
```
coverage instrument       /app/elements/SOME_ELEMENT_NAME/SOME_ELEMENT_NAME.js
coverage instrument       /app/js/FOLDER_NAME/SCRIPT_NAME.js
coverage skip                  /app/OTHER_FILES
```

**Comment by t2ym** [comment]
@maxknee You can try `include` option with `"**/app/elements/**/*.js", "**/app/js/**/*.js"`

**Comment by t2ym** [comment]
@maxknee You can try `wct-istanbul@0.14.2` with `web-component-tester@^6.6.0` as well.  With `wct-istanbul@0.12.4`, you have to use the customized `@t2ym/web-component-tester@6.0.2` to get  coverage.

**Comment by maxknee** [comment]
@t2ym Thanks for your help, adding `**/app/elements/**/.js` worked! 
Still using polymer 1 so latest version of WCT won't work but yours is.
